### ISSUE TITLE
A question about running

### ISSUE THREAD

**Issue by Liugazn** [zichengpan/SSFE-Net#2]
Dear author, hello, I am very grateful to you for making your code public, which has benefited me a lot, 
but I encountered some problems while running the code,(since I just started to contact python) 
 can you please update it your readme.sh so that you can explain more about your code?
Many thanks！！！

**Comment by zichengpan** [comment]
Hi, sorry I just saw the comment. You can run the code by using following command at the main directory. I've also updated the README file to explain it.

`sh train.sh`

**Comment by Liugazn** [comment]
thankyou for your reply！



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/11/2024 16:36 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [zichengpan/SSFE-Net] A question about running (Issue #2) |

Closed #2 as completed.
